package phrasalverbs

import (
	"github.com/ravil23/lingualynda/telegrambot/collection/schema"
)

var VocabularyVerbs = schema.NewVocabulary(
	map[schema.Term][]schema.Translation{
		"add up":                   {"быть правдоподобным", "сходиться"},
		"ask somebody out":         {"пригласить на свидание"},
		"back off":                 {"отвали"},
		"be cut off":               {"быть отрезанным от"},
		"be knocked down":          {"быть снесенным"},
		"be off":                   {"уезжать откуда-то"},
		"bend down":                {"наклониться", "нагнуться"},
		"blow out":                 {"задуть"},
		"blow something down":      {"свалить что-то"},
		"break down":               {"перестать работать", "сломаться"},
		"bring in":                 {"принести"},
		"bring up":                 {"воспитывать"},
		"burn down":                {"быть сожженым"},
		"call something off":       {"отменить что-то"},
		"calm (somebody) down":     {"успокоиться"},
		"carry on (with)":          {"продолжать делать"},
		"carry out":                {"выполнять"},
		"cash in on":               {"заработать на"},
		"catch up":                 {"не отставать"},
		"check in":                 {"зарегистрироваться"},
		"clean out":                {"обчистить", "обворовать"},
		"close down":               {"прекратить бизнес"},
		"come in":                  {"войти"},
		"come over":                {"прийти"},
		"contend with":             {"справляться с"},
		"cordon off something":     {"оцеплять территорию"},
		"count on something":       {"рассчитывать на что-то"},
		"count out":                {"не включать"},
		"crawl out":                {"выползать"},
		"cross out":                {"зачеркнуть"},
		"cut down (on something)":  {"делать что-то реже"},
		"cut in":                   {"прерывать"},
		"cut off something":        {"перестать поставки чего-либо"},
		"cut out":                  {"вырезать"},
		"cut something down":       {"срезать что-то"},
		"depend on something":      {"зависеть от чего-либо"},
		"deprive of":               {"лишать кого-то"},
		"dive in":                  {"погружаться в воду"},
		"doze off":                 {"засыпать"},
		"draw out":                 {"чересчур растягивать во времени"},
		"drive off":                {"проехать"},
		"drive on":                 {"продолжать ехать"},
		"drone on":                 {"нудно рассказывать"},
		"drop by":                  {"зайти", "навестить"},
		"drop in":                  {"заходить непреднамеренно"},
		"drop off":                 {"засыпать"},
		"drop out":                 {"прекратить дело"},
		"dwell on something":       {"долго обсуждать одну тему"},
		"dwell on":                 {"зацикливаться"},
		"eat out":                  {"поесть вне дома"},
		"factor in":                {"включить в расчеты"},
		"fall out":                 {"ссоритья"},
		"fill in":                  {"заполнять форму"},
		"fill out":                 {"заполнять форму"},
		"find out about":           {"получить информацию"},
		"find out":                 {"понять"},
		"finish off":               {"обессилеть чтобы продолжать"},
		"finish something off":     {"делать последнюю чась чего-либо"},
		"fit in with":              {"сливаться c"},
		"focus on something":       {"сконцентрироваться на чем-то"},
		"freak out":                {"беситься"},
		"frown on something":       {"нахмуриться на что-то"},
		"get by":                   {"управлять"},
		"get on something":         {"продолжать делать, то что должен"},
		"get on with":              {"ладить"},
		"get on":                   {"справиться", "прогрессировать", "садиться в транспорт"},
		"get out":                  {"избегать дела"},
		"give out":                 {"раздавать"},
		"give up":                  {"сдаваться"},
		"go off":                   {"уйти"},
		"go on and on":             {"продолжается"},
		"go on":                    {"случаться", "продолжать"},
		"go out":                   {"перестать гореть"},
		"got off":                  {"взрываться", "зазвонить"},
		"hand out":                 {"раздавать"},
		"hang on something":        {"дождаться чего-либо"},
		"hang on":                  {"секундочку"},
		"hang up":                  {"повесить трубку"},
		"happen on something":      {"случиться чему-то"},
		"have something off":       {"проводить время вне работы"},
		"hinge on something":       {"зависеть от чего-либо"},
		"hinge on":                 {"зависеть от"},
		"join in":                  {"присоединиться"},
		"jut out":                  {"торчать", "выпирать"},
		"keep on":                  {"делать постоянно повторяющейся"},
		"keep up with":             {"не отставать"},
		"kick away":                {"отбрасывать"},
		"kick off":                 {"начинать"},
		"knock down":               {"сносить"},
		"lash out":                 {"отчитывать"},
		"lead-in":                  {"введение"},
		"leave on":                 {"оставлять включенным"},
		"leave out from":           {"исключать из"},
		"led on":                   {"привели к"},
		"let in":                   {"впустить"},
		"let somebody down":        {"разочаровать кого-то"},
		"lie down":                 {"прилечь"},
		"live on":                  {"долго обсуждать одну тему"},
		"look forward to":          {"ждать с нетерпением чего-либо"},
		"look out":                 {"будь осторожен"},
		"look up at":               {"поднять взгляд на"},
		"make up":                  {"мириться"},
		"move in":                  {"заезжать"},
		"move out":                 {"съезжать"},
		"nod off":                  {"засыпать"},
		"pass out":                 {"терять сознание"},
		"pay off":                  {"заплатить", "окупаться"},
		"pick out":                 {"отделять", "перебирать"},
		"pick something up":        {"поднять что-то"},
		"pick up":                  {"подвозить", "подбирать"},
		"piss off":                 {"бесить (разговорный)"},
		"pitch in":                 {"вносить свой вклад", "помогать"},
		"play on":                  {"продолжать играть"},
		"plug in":                  {"подключить к электричеству"},
		"point out":                {"отметить", "подчеркнуть"},
		"press on":                 {"долго обсуждать одну тему"},
		"pull out":                 {"вытягивать"},
		"put off doing something":  {"причина, чтобы что-то не делать"},
		"put on":                   {"накидывать", "набирать вес", "включать (музыку)"},
		"put out":                  {"тушить"},
		"put something down":       {"положить что-то"},
		"put something off":        {"задерживать что-то"},
		"put something up":         {"повесить что-то"},
		"put up with":              {"терпеть"},
		"put up":                   {"поднимать"},
		"read on":                  {"долго обсуждать одну тему"},
		"rely on something":        {"полагаться на что-то"},
		"ride off":                 {"уехать"},
		"rip somebody off":         {"быть обманутым кем-то"},
		"round off":                {"завершить"},
		"rub out":                  {"стереть"},
		"run away from":            {"убегать от"},
		"run off":                  {"убежать"},
		"run out":                  {"закончиться"},
		"see somebody off":         {"провожать"},
		"set in":                   {"происходить"},
		"set off":                  {"начать"},
		"shake off":                {"потеряться"},
		"share out":                {"распространять"},
		"shove off":                {"убирайся"},
		"show in":                  {"представить"},
		"show off":                 {"красоваться"},
		"shrug off":                {"не считать важным"},
		"shut down":                {"прекратить бизнес"},
		"sit down":                 {"присесть"},
		"slow down":                {"двигаться медленнее"},
		"sort out":                 {"решать проблему"},
		"speak out":                {"высказаться откровенно"},
		"split off":                {"отделиться от группы"},
		"spread out":               {"распределять"},
		"spring on":                {"вывалить на"},
		"squash in":                {"втиснуться"},
		"stand out from the crowd": {"выделяться из толпы"},
		"stand up":                 {"встать"},
		"start off":                {"начать"},
		"switch off":               {"переключать на выключенное состояние"},
		"switch on":                {"переключать на включенное состояние"},
		"take in":                  {"обмануть"},
		"take off":                 {"взлетать", "снимать одежду"},
		"take something down":      {"снять что-то"},
		"tell off":                 {"ругать"},
		"tell somebody off":        {"сердито говорить"},
		"test out":                 {"протестировать"},
		"throw away":               {"выбрасывать"},
		"ticking off":              {"отчитывать"},
		"to be boxed in":           {"ограничивать"},
		"try on":                   {"примерять одежду"},
		"try out":                  {"испробовать"},
		"turn off":                 {"выключать"},
		"turn on":                  {"включать"},
		"turn out to be":           {"оказаться"},
		"turn out":                 {"выключить", "обернуться", "оказаться"},
		"turn something down":      {"ослабить мощность чего-либо", "отказаться от чего-либо"},
		"turn something up":        {"увеличить мощность чего-либо"},
		"usher in":                 {"влиться в", "начинать"},
		"wake up":                  {"разбудить"},
		"walk off":                 {"уйти"},
		"walk on":                  {"продолжать прогуливаться"},
		"work off":                 {"отрабатывать", "выплеснуть энергию"},
		"work out":                 {"делать физические упражнения", "развиваться"},
		"work something out":       {"производить какие-то расчеты"},
		"write something down":     {"записать напоминалку"},
		"yell out":                 {"вскрикивать для привлечения внимания"},
	},
)

var VocabularyEngToRus *schema.Vocabulary
var VocabularyRusToEng *schema.Vocabulary
var AllVocabularies []*schema.Vocabulary

func init() {
	VocabularyEngToRus = schema.NewEmptyVocabulary().
		Update(VocabularyVerbs)
	VocabularyRusToEng = VocabularyEngToRus.MakeInvertedVocabulary()
	AllVocabularies = []*schema.Vocabulary{VocabularyEngToRus, VocabularyRusToEng}
}
