name: CI

on:
  push:
    paths:
      - '.github/workflows/cd.yml'
      - 'telegrambot/**'
      - '!README.md'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 8
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        go-version: [1.13]

    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Get dependencies
        run: |
          cd telegrambot
          go get -v -t -d ./...
      - name: Vet checks
        run: |
          cd telegrambot
          go vet -v ./...
      - name: Test
        run: |
          cd telegrambot
          go test -v ./...
      - name: Build
        run: |
          cd telegrambot
          go build -v ./...