name: Continious integration

on:
  push:
    paths:
      - '.github/workflows/ci.yml'
      - 'bot/**'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 8
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest]
        go-version: [1.13]

    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Get dependencies
        run: |
          cd bot
          go get -v -t -d ./...
      - name: Build
        run: |
          cd bot
          go build -v ./...
      - name: Test
        run: |
          cd bot
          go test -v ./...
